### ISSUE TITLE
Create to-do list react component

### ISSUE THREAD

**Issue by lhjt** [csesoc/trainee-3-22t3#3]
- [ ] Accept user input (including adding, editing and deleting a task)
- [ ] Make request to backend to store the data
- [ ] Implement checkbox for each task (strikethrough without deletion)
- [ ] Allow reordering of tasks
- [ ] Implement progress tracker

**Comment by floyrin** [comment]
poggers
